# Generated by Django 3.1.1 on 2020-09-30 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200926_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='days_running',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='poll',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
